services:
  check_services:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check_services
    image: check_services:latest
    privileged: true
    network_mode: host
    volumes:
      - ./config.json:/check_services/config.json
      - ./exlude_service.json:/check_services/exlude_service.json
      - /etc/systemd/system/multi-user.target.wants:/etc/systemd/system/multi-user.target.wants:ro
      - /run/systemd/system:/run/systemd/system:ro
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - TZ=Etc/UTC
    restart: always

